services:
  - type: web
    name: trackmysoap
    env: python
    plan: free
    startCommand: streamlit run app.py --server.port=$PORT
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: PORT
        value: 10000
    secretFiles:
      - name: secrets
        path: .streamlit/secrets.toml