services:
  - type: web
    name: trackmysoap
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT
    envVars:
      - key: PORT
        value: 10000
      - key: GCP_CREDS
        sync: false  # tells Render not to expect this in the repo