services:
  - type: web
    name: trackmysoap
    env: python
    plan: free
    buildCommand: ""
    startCommand: streamlit run app.py --server.port=$PORT
    envVars:
      - key: PORT
        value: 10000
    secretFiles:
      - name: gcp_secrets
        path: .streamlit/secrets.toml